Fixes

diff --git a/.github/workflows/pr-check.yml b/.github/workflows/pr-check.yml
--- a/.github/workflows/pr-check.yml
+++ b/.github/workflows/pr-check.yml
@@ -11,9 +11,9 @@ jobs:
   pre-commit:
     name: pre-commit
     runs-on: ubuntu-latest
-    concurrency:
-      # group: pre-commit-${{ github.head_ref || github.ref_name }}
-      # cancel-in-progress: true
+    # concurrency:
+    # group: pre-commit-${{ github.head_ref || github.ref_name }}
+    # cancel-in-progress: true
     steps:
       - name: Run pre-commit
         uses: govuk-one-login/github-actions/code-quality/run-pre-commit@7915556fc28d7299972796de8b5888e04e05687a # my branch - change once merged
@@ -26,14 +26,17 @@ jobs:
     runs-on: ubuntu-latest
     permissions:
       contents: read
-    needs: static-checks
     steps:
+      # this can be condensed with a shared action
       - name: Checkout
         uses: actions/checkout@v6
+
       - name: Setup Node
         uses: ./.github/actions/node-setup
+
       - name: Unit tests
         run: npm run test
+
       - name: Upload coverage report
         uses: actions/upload-artifact@v4
         with:
@@ -41,33 +44,34 @@ jobs:
           path: coverage/
           retention-days: 1
 
-      - name: Sonar scan
-        runs-on: ubuntu-latest
-        needs: unit-tests
-        if: github.actor != 'dependabot[bot]'
-        # permissions:
-        #   contents: read
-        steps:
-          # - name: Collect coverage
-          #   if: ${{ github.event_name != 'pull_request' }}
-          #   uses: ./.github/workflows/run-unit-tests.yml
-          #   with:
-          #     coverage-report: true
-          - name: Run Sonar scan
-            uses: govuk-one-login/github-actions/code-quality/sonarcloud@9d6ee027d0b9167dfc25e67124951956278bb585
-            with:
-              github-token: ${{ secrets.GITHUB_TOKEN }}
-              sonar-token: ${{ secrets.SONAR_TOKEN }}
-              coverage-artifact: coverage
-              coverage-run-id: ${{ github.run_id }} # || null?
-
-      - name: Code QL
-        runs-on: ubuntu-latest
-        permissions:
-          security-events: write
-        steps:
-          - name: Run CodeQL scan
-            uses: govuk-one-login/github-actions/code-quality/codeql@f5362528578198e7851e96e0594f593beff0162e
+  sonar-scan:
+    name: Sonar scan
+    runs-on: ubuntu-latest
+    needs: unit-tests
+    if: github.actor != 'dependabot[bot]'
+    permissions:
+      contents: read
+    steps:
+      # - name: Collect coverage
+      #   if: ${{ github.event_name != 'pull_request' }}
+      #   uses: ./.github/workflows/run-unit-tests.yml
+      #   with:
+      #     coverage-report: true
+      - name: Run Sonar scan
+        uses: govuk-one-login/github-actions/code-quality/sonarcloud@9d6ee027d0b9167dfc25e67124951956278bb585
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          sonar-token: ${{ secrets.SONAR_TOKEN }}
+          coverage-artifact: coverage
+          coverage-run-id: ${{ github.run_id }} # || null?
+  codeql:
+    name: Code QL
+    runs-on: ubuntu-latest
+    permissions:
+      security-events: write
+    steps:
+      - name: Run CodeQL scan
+        uses: govuk-one-login/github-actions/code-quality/codeql@f5362528578198e7851e96e0594f593beff0162e
 
   # potential to move scans out to run on cron - and call in above job
 
@@ -75,9 +79,7 @@ jobs:
 
   # infra test placholder
 
-  # pre-merge tests (deploy pre-view stack hmrc check - test it)
   # include the cleanup action run periodically instead of cleaning straight away
-
   deploy:
     name: Deploy preview stack
     uses: ./.github/workflows/deploy-preview.yml
@@ -119,16 +121,16 @@ jobs:
 
   # think about this...
   merge-status:
-  runs-on: ubuntu-latest
-  needs: [pre-commit, unit-tests]
-  if: always()
-  steps:
-    - run: |
-        failed=()
-        [[ "${{ needs.pre-commit.result }}" != "success" ]] && failed+=("pre-commit")
-        [[ "${{ needs.unit-tests.result }}" != "success" ]] && failed+=("unit-tests")
+    runs-on: ubuntu-latest
+    needs: [pre-commit, unit-tests]
+    if: always()
+    steps:
+      - run: |
+          failed=()
+          [[ "${{ needs.pre-commit.result }}" != "success" ]] && failed+=("pre-commit")
+          [[ "${{ needs.unit-tests.result }}" != "success" ]] && failed+=("unit-tests")
 
-        if [[ ${#failed[@]} -gt 0 ]]; then
-          echo "The following jobs failed: ${failed[*]}"
-          exit 1
-        fi
+          if [[ ${#failed[@]} -gt 0 ]]; then
+            echo "The following jobs failed: ${failed[*]}"
+            exit 1
+          fi
