Adding merge-status back in so doesnt hang

diff --git a/.github/workflows/pr-check.yml b/.github/workflows/pr-check.yml
--- a/.github/workflows/pr-check.yml
+++ b/.github/workflows/pr-check.yml
@@ -117,19 +117,18 @@ jobs:
           # stack-outputs: ${{ needs.deploy.outputs.stack-outputs }}
           script: npm run test:api # might need ci and non ci versions
 
-
   # think about this...
-  # merge-status:
-  # runs-on: ubuntu-latest
-  # needs: [pre-commit, unit-tests]
-  # if: always()
-  # steps:
-  #   - run: |
-  #       failed=()
-  #       [[ "${{ needs.pre-commit.result }}" != "success" ]] && failed+=("pre-commit")
-  #       [[ "${{ needs.unit-tests.result }}" != "success" ]] && failed+=("unit-tests")
+  merge-status:
+  runs-on: ubuntu-latest
+  needs: [pre-commit, unit-tests]
+  if: always()
+  steps:
+    - run: |
+        failed=()
+        [[ "${{ needs.pre-commit.result }}" != "success" ]] && failed+=("pre-commit")
+        [[ "${{ needs.unit-tests.result }}" != "success" ]] && failed+=("unit-tests")
 
-  #       if [[ ${#failed[@]} -gt 0 ]]; then
-  #         echo "The following jobs failed: ${failed[*]}"
-  #         exit 1
-  #       fi
+        if [[ ${#failed[@]} -gt 0 ]]; then
+          echo "The following jobs failed: ${failed[*]}"
+          exit 1
+        fi
